// Code generated by protoc-gen-go. DO NOT EDIT.
// source: taskService.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TaskRequest struct {
	//@inject_tag: json:"Id" form:"Id"
	Id uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	//@inject_tag: json:"Uid" form:"Uid"
	Uid uint64 `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	//@inject_tag: json:"Title" form:"Title"
	Title string `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	//@inject_tag: json:"Content" form:"Content"
	Content string `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	//@inject_tag: json:"StartTime" form:"StartTime"
	StartTime int64 `protobuf:"varint,5,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	//@inject_tag: json:"EndTime" form:"EndTime"
	EndTime int64 `protobuf:"varint,6,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	//@inject_tag: json:"Status" form:"Status"
	Status int64 `protobuf:"varint,7,opt,name=Status,proto3" json:"Status,omitempty"`
	// @inject_tag: json:"Start" form:"Start" uri:"Start"
	Start uint32 `protobuf:"varint,8,opt,name=Start,proto3" json:"Start,omitempty"`
	// @inject_tag: json:"Limit" form:"Limit" uri:"Limit"
	Limit                uint32   `protobuf:"varint,9,opt,name=Limit,proto3" json:"Limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRequest) Reset()         { *m = TaskRequest{} }
func (m *TaskRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRequest) ProtoMessage()    {}
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73398b334343aecd, []int{0}
}

func (m *TaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRequest.Unmarshal(m, b)
}
func (m *TaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRequest.Marshal(b, m, deterministic)
}
func (m *TaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRequest.Merge(m, src)
}
func (m *TaskRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRequest.Size(m)
}
func (m *TaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRequest proto.InternalMessageInfo

func (m *TaskRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TaskRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *TaskRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TaskRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TaskRequest) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *TaskRequest) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *TaskRequest) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TaskRequest) GetStart() uint32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *TaskRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type TaskListResponse struct {
	TaskList []*TaskModel `protobuf:"bytes,1,rep,name=TaskList,proto3" json:"TaskList,omitempty"`
	// @inject_tag: json:"Count"
	Count                uint32   `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskListResponse) Reset()         { *m = TaskListResponse{} }
func (m *TaskListResponse) String() string { return proto.CompactTextString(m) }
func (*TaskListResponse) ProtoMessage()    {}
func (*TaskListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73398b334343aecd, []int{1}
}

func (m *TaskListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskListResponse.Unmarshal(m, b)
}
func (m *TaskListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskListResponse.Marshal(b, m, deterministic)
}
func (m *TaskListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskListResponse.Merge(m, src)
}
func (m *TaskListResponse) XXX_Size() int {
	return xxx_messageInfo_TaskListResponse.Size(m)
}
func (m *TaskListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskListResponse proto.InternalMessageInfo

func (m *TaskListResponse) GetTaskList() []*TaskModel {
	if m != nil {
		return m.TaskList
	}
	return nil
}

func (m *TaskListResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type TaskDetailResponse struct {
	TaskDetail           *TaskModel `protobuf:"bytes,1,opt,name=TaskDetail,proto3" json:"TaskDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TaskDetailResponse) Reset()         { *m = TaskDetailResponse{} }
func (m *TaskDetailResponse) String() string { return proto.CompactTextString(m) }
func (*TaskDetailResponse) ProtoMessage()    {}
func (*TaskDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73398b334343aecd, []int{2}
}

func (m *TaskDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDetailResponse.Unmarshal(m, b)
}
func (m *TaskDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDetailResponse.Marshal(b, m, deterministic)
}
func (m *TaskDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDetailResponse.Merge(m, src)
}
func (m *TaskDetailResponse) XXX_Size() int {
	return xxx_messageInfo_TaskDetailResponse.Size(m)
}
func (m *TaskDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDetailResponse proto.InternalMessageInfo

func (m *TaskDetailResponse) GetTaskDetail() *TaskModel {
	if m != nil {
		return m.TaskDetail
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskRequest)(nil), "services.TaskRequest")
	proto.RegisterType((*TaskListResponse)(nil), "services.TaskListResponse")
	proto.RegisterType((*TaskDetailResponse)(nil), "services.TaskDetailResponse")
}

func init() {
	proto.RegisterFile("taskService.proto", fileDescriptor_73398b334343aecd)
}

var fileDescriptor_73398b334343aecd = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x86, 0x65, 0x1b, 0x30, 0x1e, 0x4a, 0x45, 0x57, 0xa8, 0xda, 0xd2, 0x1e, 0x2c, 0x4e, 0x3e,
	0xb9, 0x12, 0x3d, 0xb6, 0x12, 0x52, 0xa1, 0x6a, 0x91, 0xe8, 0x65, 0x31, 0x52, 0x94, 0x9b, 0x13,
	0xcf, 0x61, 0x85, 0xb1, 0x89, 0x77, 0xc8, 0x6b, 0xe6, 0x01, 0xf2, 0x32, 0xd1, 0xee, 0xda, 0x10,
	0x47, 0x9c, 0xc8, 0x09, 0xfe, 0xef, 0x9f, 0xf9, 0x77, 0x77, 0xc6, 0xf0, 0x89, 0x52, 0xb5, 0xdb,
	0x60, 0xf5, 0x28, 0xef, 0x31, 0x3e, 0x54, 0x25, 0x95, 0xcc, 0x57, 0x56, 0x4e, 0x46, 0xda, 0xfb,
	0x5f, 0x66, 0x98, 0x2b, 0x6b, 0x4d, 0x9f, 0x1d, 0x18, 0x24, 0xa9, 0xda, 0x09, 0x7c, 0x38, 0xa2,
	0x22, 0xf6, 0x11, 0xdc, 0x55, 0xc6, 0x9d, 0xd0, 0x89, 0x3a, 0xc2, 0x5d, 0x65, 0x6c, 0x04, 0xde,
	0x56, 0x66, 0xdc, 0x35, 0x40, 0xff, 0x65, 0x63, 0xe8, 0x26, 0x92, 0x72, 0xe4, 0x5e, 0xe8, 0x44,
	0x81, 0xb0, 0x82, 0x71, 0xf0, 0x17, 0x65, 0x41, 0x58, 0x10, 0xef, 0x18, 0xde, 0x48, 0xf6, 0x0d,
	0x82, 0x0d, 0xa5, 0x15, 0x25, 0x72, 0x8f, 0xbc, 0x1b, 0x3a, 0x91, 0x27, 0xce, 0x40, 0xf7, 0xfd,
	0x29, 0x32, 0xe3, 0xf5, 0x8c, 0xd7, 0x48, 0xf6, 0x19, 0x7a, 0x1b, 0x4a, 0xe9, 0xa8, 0xb8, 0x6f,
	0x8c, 0x5a, 0xe9, 0xf3, 0x4d, 0x3b, 0xef, 0x87, 0x4e, 0x34, 0x14, 0x56, 0x68, 0xba, 0x96, 0x7b,
	0x49, 0x3c, 0xb0, 0xd4, 0x88, 0xe9, 0x0d, 0x8c, 0xf4, 0xe3, 0xd6, 0x52, 0x91, 0x40, 0x75, 0x28,
	0x0b, 0x85, 0x2c, 0x86, 0x7e, 0xc3, 0xb8, 0x13, 0x7a, 0xd1, 0x60, 0xc6, 0xe2, 0x7a, 0x3e, 0x71,
	0xd2, 0x8c, 0x47, 0x9c, 0x6a, 0x74, 0xf2, 0xa2, 0x3c, 0x16, 0x64, 0x66, 0x30, 0x14, 0x56, 0x4c,
	0xff, 0x01, 0xd3, 0x15, 0x4b, 0xa4, 0x54, 0xe6, 0xa7, 0xec, 0x19, 0xc0, 0x99, 0x9a, 0x29, 0x5e,
	0x4e, 0x7f, 0x55, 0x35, 0x7b, 0x72, 0xed, 0x06, 0xea, 0x95, 0xb1, 0x39, 0xc0, 0xa2, 0xc2, 0x94,
	0x50, 0x43, 0x36, 0x6e, 0x75, 0xd7, 0x5b, 0x9a, 0x7c, 0x6d, 0xd1, 0x37, 0x97, 0x98, 0xc3, 0x87,
	0xbf, 0x48, 0xda, 0x50, 0xf6, 0x01, 0x17, 0x23, 0xbe, 0xb4, 0x68, 0x6b, 0x42, 0xbf, 0xc0, 0xaf,
	0x03, 0xae, 0x3b, 0x1e, 0xb6, 0x87, 0xec, 0x5d, 0xf7, 0x87, 0x25, 0xe6, 0x78, 0x75, 0xc0, 0xef,
	0xc1, 0x6d, 0x10, 0x7f, 0xff, 0x69, 0xbe, 0x6f, 0x75, 0xd7, 0x33, 0xbf, 0x3f, 0x5e, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x7a, 0x9b, 0x35, 0x6f, 0x17, 0x03, 0x00, 0x00,
}
