// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userService.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	// @inject_tag: json:"user_name" form:"user_name" uri:"user_name"
	UserName string `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	// @inject_tag: json:"password" form:"password" uri:"password"
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	// @inject_tag: json:"password_confirm" form:"password_confirm" uri:"password_confirm"
	PasswordConfirm      string   `protobuf:"bytes,3,opt,name=PasswordConfirm,proto3" json:"PasswordConfirm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRequest) GetPasswordConfirm() string {
	if m != nil {
		return m.PasswordConfirm
	}
	return ""
}

type UserDetailResponse struct {
	UserDetail           *UserModel `protobuf:"bytes,1,opt,name=UserDetail,proto3" json:"UserDetail,omitempty"`
	Code                 uint32     `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserDetailResponse) Reset()         { *m = UserDetailResponse{} }
func (m *UserDetailResponse) String() string { return proto.CompactTextString(m) }
func (*UserDetailResponse) ProtoMessage()    {}
func (*UserDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_874b4b11a4ddc7c4, []int{1}
}

func (m *UserDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetailResponse.Unmarshal(m, b)
}
func (m *UserDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetailResponse.Marshal(b, m, deterministic)
}
func (m *UserDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetailResponse.Merge(m, src)
}
func (m *UserDetailResponse) XXX_Size() int {
	return xxx_messageInfo_UserDetailResponse.Size(m)
}
func (m *UserDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetailResponse proto.InternalMessageInfo

func (m *UserDetailResponse) GetUserDetail() *UserModel {
	if m != nil {
		return m.UserDetail
	}
	return nil
}

func (m *UserDetailResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "services.UserRequest")
	proto.RegisterType((*UserDetailResponse)(nil), "services.UserDetailResponse")
}

func init() {
	proto.RegisterFile("userService.proto", fileDescriptor_874b4b11a4ddc7c4)
}

var fileDescriptor_874b4b11a4ddc7c4 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x50, 0x4d, 0x4b, 0x03, 0x31,
	0x10, 0x65, 0x55, 0x64, 0x3b, 0x55, 0xd4, 0x11, 0x61, 0x59, 0x3c, 0x48, 0x4f, 0x3d, 0x45, 0x68,
	0x8f, 0x5e, 0xc4, 0xf5, 0xa8, 0x22, 0x91, 0x5e, 0x04, 0x0f, 0xab, 0x3b, 0x96, 0x40, 0xbb, 0x53,
	0x33, 0xa9, 0xfe, 0x11, 0x7f, 0xb0, 0x24, 0x69, 0xd4, 0xdd, 0x63, 0x4f, 0x99, 0xf7, 0xc1, 0xcb,
	0x9b, 0x81, 0x93, 0xb5, 0x90, 0x7d, 0x22, 0xfb, 0x69, 0xde, 0x48, 0xad, 0x2c, 0x3b, 0xc6, 0x5c,
	0x22, 0x94, 0xf2, 0xd8, 0x8b, 0xf7, 0xdc, 0xd0, 0x42, 0xa2, 0x36, 0x62, 0x18, 0xce, 0x84, 0xac,
	0xa6, 0x8f, 0x35, 0x89, 0xc3, 0x12, 0x72, 0x0f, 0x1f, 0xea, 0x25, 0x15, 0xd9, 0x45, 0x36, 0x1e,
	0xe8, 0x5f, 0xec, 0xb5, 0xc7, 0x5a, 0xe4, 0x8b, 0x6d, 0x53, 0xec, 0x44, 0x2d, 0x61, 0x1c, 0xc3,
	0x51, 0x9a, 0x2b, 0x6e, 0xdf, 0x8d, 0x5d, 0x16, 0xbb, 0xc1, 0xd2, 0xa7, 0x47, 0x2f, 0x80, 0x3e,
	0xf1, 0x96, 0x5c, 0x6d, 0x16, 0x9a, 0x64, 0xc5, 0xad, 0x10, 0x4e, 0x01, 0xfe, 0xd8, 0xf0, 0xf3,
	0x70, 0x72, 0xaa, 0x52, 0x6f, 0x35, 0x4b, 0xb5, 0xf5, 0x3f, 0x1b, 0x22, 0xec, 0x55, 0xdc, 0x50,
	0x28, 0x73, 0xa8, 0xc3, 0x3c, 0xf9, 0xce, 0xe2, 0x42, 0x9b, 0x0b, 0xe0, 0x35, 0x0c, 0x3c, 0xbc,
	0xe3, 0xb9, 0x69, 0xf1, 0xac, 0x9b, 0xb8, 0x59, 0xba, 0x3c, 0xef, 0xd2, 0xbd, 0x6a, 0x15, 0x1c,
	0x44, 0xf3, 0xdc, 0x88, 0x23, 0xbb, 0x55, 0xc8, 0x0d, 0x3c, 0xe7, 0xea, 0xf2, 0x2a, 0x9c, 0xfc,
	0x75, 0x3f, 0x3c, 0xd3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0x70, 0xc8, 0x66, 0xaa, 0x01,
	0x00, 0x00,
}
